import { useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { BookOpen, Plus, Play, ArrowLeft } from 'lucide-react'
import { Heading, Empty, ActionForm, Notice } from '../workspace/ui'
import { useInternal } from './hooks'
import { currentVersion, STAFF_ROLES } from './model'
import { dispatchInternal } from './store'
import { Status, StudioModal } from './Shared'
import ChapterEditor from './ChapterEditor'
import StoryPlayer from './StoryPlayer'

function AssignmentFields({ staff, chapter }) {
  return <>{[['editor', 'Editor', 'editorId'], ['reviewer', 'Reviewer', 'reviewerId']].map(([role, label, key]) => <label key={role}>{label}<select name={key} required defaultValue={chapter?.[key] || ''}><option value="" disabled>Chọn {label}</option>{staff.filter(s => s.role === role && s.active).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>)}</>
}
export function Chapters() {
  const { actor, db } = useInternal()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [creating, setCreating] = useState(false)
  const chapters = db.chapters.filter(c => `${c.number} ${currentVersion(c).title}`.toLowerCase().includes(search.toLowerCase()) && (!status || currentVersion(c).status === status))
  return <><Heading eyebrow="CONTENT STUDIO · CỐT TRUYỆN" title={actor.role === 'reviewer' ? 'Hàng đợi kiểm duyệt' : 'Thư viện chương'} description={actor.role === 'editor' ? 'Các chương được phân công cho bạn. Biên tập, chơi thử và gửi duyệt từng phiên bản.' : 'Theo dõi nội dung, người phụ trách và phiên bản đang phát hành.'}>{actor.role === 'manager' && <button className="ws-btn primary" onClick={() => setCreating(true)}><Plus size={17}/> Tạo & phân công chương</button>}</Heading><div className="ws-toolbar"><label>Tìm chương<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Số chương hoặc tên"/></label><label>Trạng thái<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="draft">Bản nháp</option><option value="pending">Chờ duyệt</option><option value="passed">Pass</option><option value="failed">Failed</option><option value="published">Đã phát hành</option></select></label></div><div className="ws-grid two">{chapters.map(chapter => { const version = currentVersion(chapter); return <article className="ws-card" key={chapter.id}><div className="ws-row"><span className="studio-eyebrow">CHƯƠNG {chapter.number} · V{version.number}</span><Status status={version.status}/></div><BookOpen size={32}/><h2>{version.title}</h2><p>{version.summary || 'Đang chờ Editor bổ sung nội dung.'}</p><p className="ws-muted">{version.scenes.length} cảnh · {chapter.publishedVersion ? `Đang phát hành v${chapter.publishedVersion}` : 'Chưa phát hành'}</p><Link className="ws-btn" to={`/internal/chapters/${chapter.id}`}>Mở chương →</Link></article> })}</div>{!chapters.length && <Empty>Không có chương phù hợp. Editor/Reviewer chỉ thấy các chương được Manager phân công.</Empty>}{creating && <StudioModal title="Tạo chương và phân công" description="Chọn số chương theo bản đồ 8 chương hiện tại. Cốt truyện mới bắt đầu ở trạng thái nháp." close={() => setCreating(false)}><ActionForm submit="Tạo chương" onSubmit={form => { dispatchInternal('CREATE_CHAPTER', { number: Number(form.get('number')), title: form.get('title'), editorId: form.get('editorId'), reviewerId: form.get('reviewerId') }); setCreating(false) }}><label>Chương<select name="number" required><option value="">Chọn chương</option>{Array.from({ length: 8 }, (_, i) => i + 1).filter(n => !db.chapters.some(c => c.number === n)).map(n => <option key={n} value={n}>Chương {n}</option>)}</select></label><label>Tên chương<input name="title" required maxLength={160}/></label><AssignmentFields staff={db.staff}/></ActionForm></StudioModal>}</>
}
export function ChapterDetail() {
  const { id } = useParams()
  const { actor, db } = useInternal()
  const [editing, setEditing] = useState(false)
  const [assigning, setAssigning] = useState(false)
  const [publishing, setPublishing] = useState(false)
  const [notice, setNotice] = useState('')
  const chapter = db.chapters.find(c => c.id === id)
  if (!chapter) return <Empty>Chương không tồn tại hoặc không được phân công cho bạn. <Link to="/internal/chapters">Về thư viện</Link></Empty>
  const version = currentVersion(chapter)
  const base = { chapterId: chapter.id, revision: chapter.revision }
  const run = (type, payload, success) => { try { dispatchInternal(type, { ...base, ...payload }); setNotice(success) } catch (err) { setNotice(err.message) } }
  return <><Link className="ws-text-link" to="/internal/chapters"><ArrowLeft size={16}/> Thư viện chương</Link><Heading eyebrow={`CHƯƠNG ${chapter.number} · PHIÊN BẢN ${version.number}`} title={version.title} description={version.summary}><Status status={version.status}/></Heading><Notice text={notice}/><div className="studio-editor-grid"><div>{editing ? <ChapterEditor chapter={chapter} onCancel={() => setEditing(false)} onSaved={() => { setEditing(false); setNotice('Đã lưu bản nháp mới. Cần gửi duyệt trước khi phát hành.') }}/> : <section className="ws-card"><h2>Nội dung phiên bản hiện tại</h2>{version.scenes.length ? version.scenes.map((scene, i) => <article className="studio-version" key={scene.id}><span className="studio-eyebrow">CẢNH {i + 1} · {scene.speaker || 'Người dẫn chuyện'}</span><p style={{ whiteSpace: 'pre-wrap' }}>{scene.text}</p>{scene.minigame && <span className="ws-pill">Mini game Minh · Lịch học và ca làm</span>}{scene.choices.map((choice, n) => <p key={n}>↳ {choice.label} · {choice.next === 'end' ? 'Kết thúc' : choice.next ? `Cảnh ${version.scenes.findIndex(s => s.id === choice.next) + 1}` : 'Cảnh tiếp theo'}</p>)}</article>) : <Empty>Chưa có nội dung. Editor được phân công có thể bắt đầu biên tập.</Empty>}</section>}
    {actor.role === 'reviewer' && version.status === 'pending' && <section className="ws-card"><h2>Đánh giá v{version.number}</h2>{version.demoBy.includes(actor.id) ? <ActionForm submit="Gửi đánh giá" onSubmit={form => { dispatchInternal('REVIEW', { ...base, decision: form.get('decision'), comment: form.get('comment') }); setNotice('Đã lưu đánh giá cho đúng phiên bản này.') }}><label>Kết luận<select name="decision" required defaultValue=""><option value="" disabled>Chọn kết luận</option><option value="passed">Pass · Đủ điều kiện phát hành</option><option value="failed">Failed · Cần sửa và gửi duyệt lại</option></select></label><label>Nhận xét<textarea name="comment" required maxLength={4000} placeholder="Nội dung, lựa chọn, trải nghiệm demo và điểm cần sửa…"/></label></ActionForm> : <Empty>Chơi hết một nhánh demo và bấm “Ghi nhận hoàn thành demo” để mở phần đánh giá.<br/><Link className="ws-btn" to={`/internal/chapters/${id}/demo`}>Chơi demo v{version.number}</Link></Empty>}</section>}
    <section className="ws-card"><h2>Lịch sử phiên bản</h2>{chapter.versions.toReversed().map(v => <details className="studio-version" key={v.number}><summary>v{v.number} · {v.title} <Status status={v.status}/>{chapter.publishedVersion === v.number ? ' · Đang phục vụ người chơi' : ''}</summary><p>{new Date(v.createdAt).toLocaleString('vi-VN')} · {v.scenes.length} cảnh</p>{v.review && <blockquote><b>{v.review.reviewerName} · {v.review.decision === 'passed' ? 'Pass' : 'Failed'}</b><p style={{ whiteSpace: 'pre-wrap' }}>{v.review.comment}</p></blockquote>}{v.scenes.length > 0 && <Link className="ws-text-link" to={`/internal/chapters/${id}/demo?version=${v.number}`}>Xem demo phiên bản này →</Link>}</details>)}</section></div><aside className="ws-card"><h2>Phụ trách chương</h2>{[['editorId', 'editor'], ['reviewerId', 'reviewer']].map(([key, role]) => { const staff = db.staff.find(s => s.id === chapter[key]); return <p key={key}><b>{STAFF_ROLES[role]}</b><br/>{staff?.name || 'Chưa phân công'}{staff && !staff.active && ' · Đã khóa'}</p> })}<p>{chapter.publishedVersion ? `Người chơi đang nhận v${chapter.publishedVersion}.` : 'Chưa có phiên bản nội bộ được phát hành.'}</p><div className="ws-form">{version.scenes.length > 0 && <Link className="ws-btn" to={`/internal/chapters/${id}/demo`}><Play size={16}/> Chơi demo v{version.number}</Link>}{actor.role === 'editor' && version.status !== 'pending' && !editing && <button className="ws-btn primary" onClick={() => setEditing(true)}>Biên tập bản mới</button>}{actor.role === 'editor' && version.status === 'draft' && !editing && <button className="ws-btn" disabled={!version.scenes.length} onClick={() => run('SUBMIT_REVIEW', {}, 'Đã gửi chương cho Reviewer.')}>Gửi duyệt v{version.number}</button>}{actor.role === 'manager' && <><button className="ws-btn" onClick={() => setAssigning(true)}>Phân công lại</button><button className="ws-btn primary" disabled={version.status !== 'passed'} onClick={() => setPublishing(true)}>Phát hành v{version.number}</button><small>Chỉ bản mới nhất đã Pass mới được phát hành.</small></>}{actor.role === 'admin' && <p className="ws-muted">Chế độ giám sát: không sửa, duyệt hoặc publish nội dung.</p>}</div></aside></div>
    {assigning && <StudioModal title="Phân công chương" description="Việc đổi người phụ trách không sửa nội dung hoặc kết quả duyệt đã lưu." close={() => setAssigning(false)}><ActionForm onSubmit={form => { dispatchInternal('ASSIGN_CHAPTER', { ...base, editorId: form.get('editorId'), reviewerId: form.get('reviewerId') }); setAssigning(false) }}><AssignmentFields staff={db.staff} chapter={chapter}/></ActionForm></StudioModal>}
    {publishing && <StudioModal title={`Phát hành chương ${chapter.number} · v${version.number}`} description="Bản đã Pass này sẽ được dùng trong trang chơi trên trình duyệt hiện tại. Bản phát hành trước vẫn có trong lịch sử." close={() => setPublishing(false)}><ActionForm submit="Xác nhận phát hành" onSubmit={() => { dispatchInternal('PUBLISH', base); setPublishing(false); setNotice('Đã phát hành. Người học có quyền vào chương sẽ thấy phiên bản này.') }}><p>{version.title}</p><p>Reviewer: {version.review?.reviewerName}</p></ActionForm></StudioModal>}
  </>
}
export function ChapterDemo() {
  const { id } = useParams()
  const [params] = useSearchParams()
  const { actor, db } = useInternal()
  const chapter = db.chapters.find(c => c.id === id)
  const version = chapter && (params.has('version') ? chapter.versions.find(v => v.number === Number(params.get('version'))) : currentVersion(chapter))
  if (!version) return <Empty>Không tìm thấy phiên bản trong phạm vi của bạn.</Empty>
  const canRecord = ['editor', 'reviewer'].includes(actor.role) && version.number === currentVersion(chapter).number
  return <><Link className="ws-text-link" to={`/internal/chapters/${id}`}><ArrowLeft size={16}/> Quay lại chương và đánh giá</Link><Heading eyebrow={`CHƠI THỬ · CHƯƠNG ${chapter.number} · V${version.number}`} title={version.title} description="Demo dùng đúng nội dung đã lưu của phiên bản đang xem. Các chỉ số tài chính trong mini game là dữ liệu kịch bản."/><StoryPlayer key={`${id}-${version.number}`} version={version} onFinish={canRecord ? () => dispatchInternal('COMPLETE_DEMO', { chapterId: id, revision: chapter.revision, version: version.number }) : undefined}/></>
}
