import { useState, useSyncExternalStore } from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, CheckCircle, Clock, Radio, Users } from 'lucide-react'
import { Heading, Empty, ActionForm } from '../workspace/ui'
import { getSnapshot, subscribe } from '../workspace/pendingBackend'
import { accountPlans } from '../workspace/model'
import { useInternal } from './hooks'
import { currentVersion, STAFF_ROLES } from './model'
import { createStaff, dispatchInternal } from './store'
import { Status, StudioModal } from './Shared'

export function InternalOverview() {
  const { actor, db } = useInternal()
  const pending = db.chapters.filter(c => currentVersion(c).status === 'pending')
  const passed = db.chapters.filter(c => currentVersion(c).status === 'passed')
  const published = db.chapters.filter(c => c.publishedVersion)
  const next = actor.role === 'reviewer' ? pending : actor.role === 'manager' ? passed : db.chapters.filter(c => ['draft', 'failed'].includes(currentVersion(c).status))
  const copy = { editor: ['Từ ý tưởng đến câu chuyện.', 'Soạn cảnh, thêm lựa chọn, chơi thử rồi gửi từng phiên bản cho Reviewer.'], reviewer: ['Một vòng duyệt thật kỹ.', 'Chơi demo của phiên bản được giao, ghi nhận xét và đánh giá Pass hoặc Failed.'], manager: ['Đúng người. Đúng phiên bản.', 'Phân công đội ngũ và đưa các chương đã Pass đến người chơi.'], admin: ['Quan sát toàn bộ hành trình.', 'Theo dõi nhân sự, trạng thái tài khoản, giao dịch mô phỏng và tiến độ phát hành với quyền chỉ đọc.'] }[actor.role]
  return <><Heading eyebrow={`CONTENT STUDIO · ${STAFF_ROLES[actor.role].toUpperCase()}`} title={`Chào ${actor.name.split(' · ')[0]}!`} description="Không gian làm việc nội bộ của FinTeen."/><section className="ws-hero"><div><span className="ws-pill">{actor.role === 'admin' ? 'Giám sát · Chỉ đọc' : 'Biên tập → Kiểm duyệt → Phát hành'}</span><h2>{copy[0]}</h2><p>{copy[1]}</p><Link className="ws-btn primary" to="/internal/chapters">Mở danh sách chương →</Link></div><BookOpen className="ws-hero-art"/></section><div className="ws-grid three">{[[BookOpen, 'Chương trong phạm vi', db.chapters.length], [Clock, 'Đang chờ duyệt', pending.length], [Radio, 'Chương đã phát hành', published.length]].map(([Icon, label, value]) => <article className="ws-card ws-stat" key={label}><Icon/><p>{label}</p><strong>{value}</strong></article>)}</div><section className="ws-card"><h2>{actor.role === 'admin' ? 'Tiến độ gần đây' : 'Việc cần xử lý'}</h2>{(actor.role === 'admin' ? db.chapters : next).length ? (actor.role === 'admin' ? db.chapters : next).map(c => <div className="ws-list-row" key={c.id}><Link className="ws-text-link" to={`/internal/chapters/${c.id}`}>Chương {c.number} · {currentVersion(c).title}</Link><Status status={currentVersion(c).status}/></div>) : <Empty>Không có công việc đang chờ trong phạm vi của bạn.</Empty>}</section></>
}
export function StaffDirectory() {
  const { actor, db } = useInternal()
  const [search, setSearch] = useState('')
  const [creating, setCreating] = useState(false)
  const [editing, setEditing] = useState(null)
  const manager = actor.role === 'manager'
  const rows = db.staff.filter(s => `${s.name} ${s.email} ${STAFF_ROLES[s.role]}`.toLowerCase().includes(search.toLowerCase()))
  return <><Heading eyebrow="ĐỘI NGŨ NỘI BỘ" title="Nhân sự & trách nhiệm" description={manager ? 'Tạo tài khoản Editor/Reviewer, gán vai và khóa hoặc mở tài khoản. Admin/Manager được tạo sẵn.' : 'Theo dõi trạng thái nhân sự. Admin không cấp vai hoặc thay đổi tài khoản.'}>{manager && <button className="ws-btn primary" onClick={() => setCreating(true)}>+ Tạo nhân sự</button>}</Heading><div className="ws-toolbar"><label>Tìm nhân sự<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tên, email hoặc vai"/></label></div><section className="ws-card"><div className="ws-table-wrap"><table><thead><tr><th>Nhân sự</th><th>Vai</th><th>Trạng thái</th><th>Chương được giao</th>{manager && <th>Thao tác</th>}</tr></thead><tbody>{rows.map(s => <tr key={s.id}><td><strong>{s.name}</strong><small>{s.email}</small></td><td>{STAFF_ROLES[s.role]}</td><td>{s.active ? 'Hoạt động' : 'Đã khóa'}</td><td>{db.chapters.filter(c => c.editorId === s.id || c.reviewerId === s.id).map(c => <div key={c.id}><Link className="ws-text-link" to={`/internal/chapters/${c.id}`}>Chương {c.number}</Link></div>)}</td>{manager && <td>{['editor', 'reviewer'].includes(s.role) ? <button className="ws-btn" onClick={() => setEditing(s)}>Quản lý</button> : 'Tài khoản hệ thống'}</td>}</tr>)}</tbody></table></div>{!rows.length && <Empty>Không tìm thấy nhân sự.</Empty>}</section>{manager && <section className="ws-card"><Users/><h2>Phân công theo từng chương</h2><p>Mỗi chương có một Editor và một Reviewer. Mở chương để thay người phụ trách; cần phân công lại trước khi đổi vai nhân sự.</p><Link className="ws-text-link" to="/internal/chapters">Mở thư viện chương →</Link></section>}
    {creating && <StudioModal title="Tạo tài khoản nội bộ" description="Tài khoản dùng được ngay trên trình duyệt này. Chưa gửi email mời vì chưa có backend." close={() => setCreating(false)}><ActionForm submit="Tạo tài khoản" onSubmit={async form => { await createStaff({ name: form.get('name'), email: form.get('email'), role: form.get('role'), password: form.get('password') }); setCreating(false) }}><label>Họ tên<input name="name" required maxLength={80}/></label><label>Email<input name="email" type="email" required autoComplete="off"/></label><label>Vai<select name="role"><option value="editor">Game Editor</option><option value="reviewer">Game Reviewer</option></select></label><label>Mật khẩu demo ban đầu<input name="password" type="password" minLength={8} required autoComplete="new-password"/><small>Tối thiểu 8 ký tự. Lưu lại để đưa cho người dùng thử tài khoản.</small></label></ActionForm></StudioModal>}
    {editing && <StudioModal title={`Quản lý · ${editing.name}`} description="Thay đổi sẽ vô hiệu phiên đăng nhập cũ. Đổi vai yêu cầu phân công lại các chương trước." close={() => setEditing(null)}><ActionForm onSubmit={form => { dispatchInternal('UPDATE_STAFF', { id: editing.id, role: form.get('role'), active: form.get('status') === 'active' }); setEditing(null) }}><label>Vai<select name="role" defaultValue={editing.role}><option value="editor">Game Editor</option><option value="reviewer">Game Reviewer</option></select></label><label>Trạng thái<select name="status" defaultValue={editing.active ? 'active' : 'locked'}><option value="active">Hoạt động / Mở khóa</option><option value="locked">Khóa tài khoản</option></select></label></ActionForm></StudioModal>}
  </>
}
export function Publications() {
  const { db, actor } = useInternal()
  const ready = db.chapters.filter(c => currentVersion(c).status === 'passed')
  const live = db.chapters.filter(c => c.publishedVersion)
  return <><Heading eyebrow="PHÁT HÀNH NỘI DUNG" title="Từ bản duyệt đến người chơi" description="Bản phát hành được giữ nguyên khi Editor sửa bản tiếp theo. Chỉ Manager được publish phiên bản đã Pass."/><section className="ws-card"><h2><CheckCircle size={20}/> Sẵn sàng phát hành · {ready.length}</h2>{ready.length ? ready.map(c => <div className="ws-list-row" key={c.id}><span>Chương {c.number} · {currentVersion(c).title}<small>v{currentVersion(c).number} · Reviewer: {currentVersion(c).review.reviewerName}</small></span><Link className="ws-btn" to={`/internal/chapters/${c.id}`}>{actor.role === 'manager' ? 'Kiểm tra & phát hành' : 'Xem chi tiết'}</Link></div>) : <Empty>Chưa có phiên bản mới đạt Pass.</Empty>}</section><section className="ws-card"><h2>Đang phát hành · {live.length}</h2>{live.length ? live.map(c => { const v = c.versions.find(v => v.number === c.publishedVersion); return <div className="ws-list-row" key={c.id}><span>Chương {c.number} · {v.title}<small>v{v.number} · {new Date(v.publishedAt).toLocaleString('vi-VN')}</small></span><Link className="ws-text-link" to={`/internal/chapters/${c.id}/demo?version=${v.number}`}>Xem bản phát hành →</Link></div> }) : <Empty>Chưa phát hành chương nội bộ nào. Gameplay chương 1–2 có sẵn vẫn hoạt động.</Empty>}</section></>
}
export function AuditLog() {
  const { db } = useInternal()
  const [search, setSearch] = useState('')
  const rows = db.audit.toReversed().filter(e => `${e.actorName} ${e.detail} ${e.actorRole}`.toLowerCase().includes(search.toLowerCase()))
  return <><Heading eyebrow="THEO DÕI HOẠT ĐỘNG" title="Nhật ký thao tác" description="Ghi nhận tạo tài khoản, phân công, biên tập, chơi demo, duyệt và phát hành trong phạm vi được phép."/><div className="ws-toolbar"><label>Tìm nhật ký<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nhân sự, vai hoặc nội dung thao tác"/></label></div><section className="ws-card"><div className="ws-table-wrap"><table><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Thao tác</th><th>Chương</th></tr></thead><tbody>{rows.map(e => <tr key={e.id}><td>{new Date(e.at).toLocaleString('vi-VN')}</td><td>{e.actorName}<small>{STAFF_ROLES[e.actorRole]}</small></td><td style={{ whiteSpace: 'pre-wrap' }}>{e.detail}</td><td>{e.chapterId && <Link className="ws-text-link" to={`/internal/chapters/${e.chapterId}`}>Mở chương</Link>}</td></tr>)}</tbody></table></div>{!rows.length && <Empty>Chưa có thao tác phù hợp. Các hành động thực hiện trong bản thử sẽ xuất hiện tại đây.</Empty>}</section></>
}
export function AccountMonitor() {
  const { db } = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
  const [search, setSearch] = useState('')
  const accounts = db.accounts.filter(a => `${a.name} ${a.email}`.toLowerCase().includes(search.toLowerCase()))
  const purchases = db.events.filter(e => e.type === 'plan_activated').toReversed()
  return <><Heading eyebrow="ADMIN · CHỈ ĐỌC" title="Tài khoản & giao dịch" description="Trạng thái tài khoản người lớn và kích hoạt gói mô phỏng. Không hiển thị danh tính hoặc kết quả từng trẻ."/><div className="ws-grid three"><article className="ws-card ws-stat"><Users/><p>Tài khoản người lớn</p><strong>{db.accounts.length}</strong></article><article className="ws-card ws-stat"><BookOpen/><p>Người học đang hoạt động · Tổng hợp</p><strong>{db.learners.filter(l => l.status === 'active').length}</strong></article><article className="ws-card ws-stat"><CheckCircle/><p>Lượt kích hoạt gói thử</p><strong>{purchases.length}</strong></article></div><div className="ws-toolbar"><label>Tìm tài khoản người lớn<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tên hoặc email"/></label></div><section className="ws-card"><h2>Tài khoản người lớn</h2><div className="ws-table-wrap"><table><thead><tr><th>Người dùng</th><th>Gói / Vai</th><th>Trạng thái trong bản thử</th></tr></thead><tbody>{accounts.map(a => <tr key={a.id}><td>{a.name}<small>{a.email}</small></td><td>{accountPlans(a).map(p => p === 'parent' ? 'Parent' : 'Teacher').join(' + ') || 'Guest'}</td><td>Đã đăng ký{accountPlans(a).length ? ' · Đã kích hoạt gói thử' : ' · Chưa có gói'}</td></tr>)}</tbody></table></div>{!accounts.length && <Empty>Chưa có tài khoản phù hợp trên trình duyệt này.</Empty>}</section><section className="ws-card"><h2>Giao dịch / kích hoạt mô phỏng</h2><p>Chưa có giao dịch thanh toán thật, giá hoặc doanh thu. Các dòng dưới là sự kiện kích hoạt gói thử.</p>{purchases.length ? purchases.map(e => <div className="ws-list-row" key={e.id}><span>{db.accounts.find(a => a.id === e.ownerId)?.email || 'Tài khoản không còn trong dữ liệu'}<small>{e.detail}</small></span><span>{new Date(e.at).toLocaleString('vi-VN')}<small>Mô phỏng · Không thu tiền</small></span></div>) : <Empty>Chưa có lượt kích hoạt gói thử.</Empty>}</section></>
}
