import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, BookOpen, Clock, Wallet, RotateCcw } from 'lucide-react';
import { chapterFourChoices, chapterFourEndings, chapterFourOutcome } from './chapterFourStory';
import './chapter-four-story.css';

const cash=value=>`${value.toLocaleString('vi-VN')}đ`;
const icons={wallet:Wallet,book:BookOpen,clock:Clock};

export function ChapterFourMiniGame({onComplete}) {
  const [phase,setPhase]=useState('intro'),[choice,setChoice]=useState(null),[frame,setFrame]=useState(0);
  const titleRef=useRef(null);
  const ending=chapterFourEndings[choice];
  const selected=chapterFourChoices.find(item=>item.id===choice);
  useEffect(()=>{titleRef.current?.focus({preventScroll:true});},[phase,frame]);
  function go(next){setPhase(next);window.scrollTo(0,0);}
  function reset(){setChoice(null);setFrame(0);go('intro');}
  return <main className="c4s"><div className="c4s-shell"><header><span className="c4s-brand">f. <b>finteen</b></span><span>CHƯƠNG 4 <b>Công việc đầu tiên</b></span><button onClick={reset} aria-label="Chơi lại đoạn truyện"><RotateCcw size={18}/></button></header>
    <div className="c4s-breadcrumb">Ngày hội nghề nghiệp <span>→</span> Hiểu tiền công <span>→</span><b>Thời gian hay tiền bạc?</b></div>
    {phase==='intro'&&<section className="c4s-scene c4s-intro"><img src="/images/career-match/career-fair-kawaii-v2.png" alt="Minh cùng Linh và Mai sau ngày hội nghề nghiệp"/><div className="c4s-shade"/><div className="c4s-scene-label">CẢNH 4.3 · CHIỀU THỨ SÁU</div><div className="c4s-dialogue"><span>MINH · CÂU CHUYỆN ĐẾN LÚC NÀY</span><h1 ref={titleRef} tabIndex={-1}>Ca làm đầu tiên.<br/>Bài kiểm tra cũng sắp tới.</h1><p>Ở ngày hội nghề nghiệp, Minh chọn phụ sự kiện. Anh Quân đã giải thích: làm đủ ca được <b>120.000đ</b>, trừ <b>20.000đ tiền xe</b> thì giữ lại <b>100.000đ</b>.</p><p>Nhưng ca chiều thứ Bảy lại trùng buổi ôn bài với Linh. Thứ Hai, Minh có bài kiểm tra.</p><div className="c4s-mother-note">Mẹ dặn trước: “Con được thử làm thêm, nhưng nếu bỏ ôn bài và kết quả sa sút thì tháng này phải tạm nghỉ để học lại nhé.”</div><button className="c4s-primary" onClick={()=>go('choice')}>Xem tin nhắn và chọn cách xử lý <ArrowRight size={18}/></button><small>Chỉ 1 quyết định · Khoảng 3 phút · Kết thúc bằng một cảnh truyện</small></div></section>}
    {phase==='choice'&&<section className="c4s-choice"><div className="c4s-heading"><span>CHỈ CẦN CHỌN MỘT CÁCH XỬ LÝ</span><h1 ref={titleRef} tabIndex={-1}>Chiều thứ Bảy, Minh sẽ làm gì?</h1><p>Đọc hai lời nhắn. Chọn một phương án, rồi xem câu chuyện xảy ra.</p></div><div className="c4s-messages"><article><span className="c4s-person c4s-linh">L</span><div><b>Linh · Bạn cùng lớp</b><p>“13–14h30 mai nhóm ôn hai dạng bài khó đó. Nếu không ôn, vào bài kiểm tra thứ Hai dễ bị vướng lắm.”</p></div></article><article><span className="c4s-person">Q</span><div><b>Anh Quân · Người phụ trách</b><p>“Ca làm 13–17h. Nếu bận ôn bài, em xin nghỉ tuần này hoặc làm nửa ca 15–17h cũng được. Nhưng nửa ca chỉ nhận 60 nghìn, tiền xe vẫn 20 nghìn nhé.”</p></div></article></div><details className="c4s-reminder"><summary>Đọc lại lời mẹ dặn</summary><p>“Con được thử làm thêm, nhưng nếu bỏ ôn bài và kết quả sa sút thì tháng này phải tạm nghỉ để học lại nhé.”</p></details><div className="c4s-options">{chapterFourChoices.map((item,index)=>{const Icon=icons[item.icon];return <button key={item.id} aria-pressed={choice===item.id} className={choice===item.id?'selected':''} onClick={()=>setChoice(item.id)}><span className="c4s-option-top"><Icon size={24}/><small>PHƯƠNG ÁN {index+1}</small><i>{choice===item.id?'✓':''}</i></span><h2>{item.label}</h2><strong>{cash(item.cash)} <small>giữ lại tuần này</small></strong><p className="c4s-time">{item.time}</p><p>{item.hint}</p></button>;})}</div><div className="c4s-confirm"><p role="status">{selected?<>Bạn chọn: <b>{selected.label}</b></>:'Chọn một thẻ phía trên để tiếp tục.'}</p><button className="c4s-primary" disabled={!choice} onClick={()=>{setFrame(0);go('ending');}}>Chọn cách này · Xem cảnh kết <ArrowRight size={18}/></button></div></section>}
    {phase==='ending'&&ending&&<section className={`c4s-scene c4s-ending c4s-ending-${choice}`} key={frame}><img src="/images/career-match/minh-mom-ending-v1.png" alt="Minh cùng mẹ xem bài kiểm tra ở phòng khách"/><div className="c4s-shade"/><div className="c4s-scene-label">{ending.frames[frame].when}</div><div className="c4s-story-prop"><span>{frame===0?'KẾT QUẢ BÀI KIỂM TRA':frame===1?'QUYẾT ĐỊNH TRONG GIA ĐÌNH':'TIỀN GIỮ ĐƯỢC TRONG THÁNG'}</span><strong>{frame===0?`${ending.grade}/10`:frame===1?(ending.workAllowed?'Được làm tiếp':'Tạm dừng làm thêm'):cash(ending.total)}</strong><small>{ending.frames[frame].prop}</small></div><div className="c4s-dialogue"><span>{ending.frames[frame].speaker.toUpperCase()}</span><h1 ref={titleRef} tabIndex={-1}>{frame===2?ending.title:frame===0?'Tờ bài kiểm tra được trả lại.':'Một cuộc nói chuyện với mẹ.'}</h1><p>{ending.frames[frame].text}</p><div className="c4s-dialogue-actions"><span className="c4s-dots" aria-label={`Đoạn ${frame+1} trên 3`}>{[0,1,2].map(i=><i key={i} className={frame===i?'active':''}/>)}</span><button className="c4s-primary" onClick={()=>frame<2?setFrame(frame+1):go('return')}>{frame<2?'Tiếp tục câu chuyện':'Trở lại mạch truyện chương 4'} <ArrowRight size={18}/></button></div></div></section>}
    {phase==='return'&&ending&&<section className="c4s-return"><div className="c4s-return-art"><img src="/images/career-match/career-fair-kawaii-v2.png" alt="Minh trở lại trò chuyện cùng Mai và Linh"/></div><div className="c4s-return-copy"><span>CẢNH NỐI · TRỞ LẠI CÂU CHUYỆN CHƯƠNG 4</span><h1 ref={titleRef} tabIndex={-1}>Một công việc không chỉ có tiền công.</h1><blockquote><b>Mai</b>“Sau tháng vừa rồi, cậu sẽ nhìn thêm điều gì khi chọn một công việc: lịch học, kỹ năng học được, hay chỉ số tiền hôm nay?”</blockquote><p><b>Minh:</b> {choice==='work'?'“Mình cần tính cả khả năng tiếp tục làm. Kiếm được hôm nay mà không giữ được việc học thì kế hoạch kiếm tiền cũng đứt đoạn.”':choice==='study'?'“Có lúc chưa nhận tiền ngay lại giúp mình giữ cơ hội về sau. Mình muốn chọn việc hợp với lịch học.”':'“Mình sẽ hỏi kỹ điều kiện và thử trao đổi. Không phải lúc nào cũng chỉ có làm hết hoặc nghỉ hẳn.”'}</p><div className="c4s-link-next"><BookOpen size={21}/><p><b>Dẫn vào cảnh 4.4 · So sánh cơ hội nghề nghiệp</b>Minh mang trải nghiệm này để cân nhắc thu nhập, thời gian và kỹ năng khi nhìn lại ba lời mời.</p></div><div className="c4s-dialogue-actions"><button className="c4s-secondary" onClick={()=>{setChoice(null);go('choice');}}><ArrowLeft size={17}/> Thử lựa chọn khác</button>{onComplete?<button className="c4s-primary" onClick={()=>onComplete(chapterFourOutcome(choice))}>Tiếp tục chương 4 <ArrowRight size={17}/></button>:<button className="c4s-primary" onClick={reset}>Chơi lại đoạn truyện <RotateCcw size={17}/></button>}</div><small>Đã hoàn thành đoạn chơi thử của cảnh 4.3.</small></div></section>}
    <footer><span>CHƯƠNG 4 / THU NHẬP · THỜI GIAN · ĐẦU TƯ VÀO BẢN THÂN</span><span>Điểm và thu nhập là kết quả của kịch bản giả lập.</span></footer>
  </div></main>;
}
